# Generated by Django 5.1.7 on 2025-03-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.IntegerField(db_index=True, max_length=13)),
                ('meter_serial_number', models.CharField(db_index=True, max_length=10)),
                ('reading_date', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=10)),
                ('flow_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KrakenApp.flowfile')),
            ],
        ),
    ]
