# Generated by Django 5.1.7 on 2025-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KrakenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='mpan_core',
            field=models.IntegerField(db_index=True),
        ),
    ]
